[package]
name = "pomodoro"
version = "0.1.0"
authors = ["giorgi.rostomashvili <giorgi.rostomashvili@inthepocket.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4"